import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ContentBundle } from "./types";

export function emitProgressionReport(bundle: ContentBundle): string {
  const lines: string[] = [];
  lines.push("# Canonical progression content report");
  lines.push("");
  lines.push("Generated by `tools/content-build`. Not a source file.");
  lines.push("");
  lines.push("- contentHash: `" + bundle.contentHash + "`");
  lines.push("- package: `" + bundle.packageId + "` " + bundle.packageVersion);
  lines.push("");
  lines.push("## Counts");
  lines.push("");
  lines.push("| Kind | Count |");
  lines.push("| --- | ---: |");
  lines.push("| stats | " + String(Object.keys(bundle.stats).length) + " |");
  lines.push("| classes | " + String(Object.keys(bundle.classes).length) + " |");
  lines.push("| branches | " + String(Object.keys(bundle.branches).length) + " |");
  lines.push("| level curves | " + String(Object.keys(bundle.levelCurves).length) + " |");
  lines.push("| timelines | " + String(Object.keys(bundle.progressionTimelines).length) + " |");
  lines.push("| auto-attacks | " + String(Object.keys(bundle.autoAttacks).length) + " |");
  lines.push("| abilities | " + String(Object.keys(bundle.abilities).length) + " |");
  lines.push("| effect definitions | " + String(Object.keys(bundle.effectDefinitions).length) + " |");
  lines.push("| talent trees | " + String(Object.keys(bundle.talentTrees).length) + " |");
  lines.push("| talent nodes | " + String(Object.keys(bundle.talentNodes).length) + " |");
  lines.push("| reference builds | " + String(Object.keys(bundle.referenceBuilds).length) + " |");
  lines.push("| enemy scaling profiles | " + String(Object.keys(bundle.enemyScalingProfiles).length) + " |");
  lines.push("| xp rewards | " + String(Object.keys(bundle.xpRewards).length) + " |");
  lines.push("| equipment modifier categories | " + String(Object.keys(bundle.equipmentModifierCategories).length) + " |");
  lines.push("");
  lines.push("## Production classes");
  lines.push("");
  const classIds = Object.keys(bundle.classes).sort();
  for (let i = 0; i < classIds.length; i++) {
    const id = classIds[i];
    if (id.indexOf("class.") !== 0) {
      continue;
    }
    const cls = bundle.classes[id];
    lines.push(
      "- `" +
        id +
        "` selectable=" +
        String(cls.rosterSelectable !== false) +
        " resource=" +
        String(cls.resourceType ?? "") +
        " tree=" +
        String(cls.classTreeId ?? ""),
    );
  }
  lines.push("");
  lines.push("Client and server bundles share this hash. Generated Godot Resources under `client/content/generated/` are conveniences, not source.");
  lines.push("");
  return lines.join("\n");
}

export function emitGodotResources(bundle: ContentBundle, outDir: string): void {
  mkdirSync(outDir, { recursive: true });
  writeResourceFolder(outDir, "stats", bundle.stats);
  writeResourceFolder(outDir, "classes", bundle.classes);
  writeResourceFolder(outDir, "branches", bundle.branches);
  writeFileSync(
    join(outDir, "catalog.tres"),
    [
      "[gd_resource type=\"Resource\" format=3]",
      "",
      "[resource]",
      "resource_name = " + JSON.stringify("canonical_catalog_" + bundle.contentHash.slice(0, 12)),
      "",
    ].join("\n"),
    "utf8",
  );
}

function writeResourceFolder(outDir: string, folder: string, map: Record<string, { id: string }>): void {
  const dir = join(outDir, folder);
  mkdirSync(dir, { recursive: true });
  const ids = Object.keys(map).sort();
  for (let i = 0; i < ids.length; i++) {
    const id = ids[i];
    const file = join(dir, id.replace(/\./g, "_") + ".tres");
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(
      file,
      [
        "[gd_resource type=\"Resource\" format=3]",
        "",
        "[resource]",
        "resource_name = " + JSON.stringify(id),
        "",
      ].join("\n"),
      "utf8",
    );
  }
}

export function writeGeneratedConveniences(
  bundle: ContentBundle,
  reportPath: string,
  godotDir: string,
): void {
  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, emitProgressionReport(bundle), "utf8");
  emitGodotResources(bundle, godotDir);
}
