import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { canonicalize } from "./canonical";
import { hashCanonical } from "./hash";
import { DEFAULT_MANIFEST, type ContentPackageManifest } from "./registry";
import type { ContentBundle, ContentPackage, ContentPayload } from "./types";

export const CONTENT_SCHEMA_VERSION = 1;

export interface BuildPackageOptions {
  manifest?: ContentPackageManifest;
  developmentOnly?: string[];
  buildTimestamp?: string;
}

export function hashedPayload(payload: ContentPayload): ContentPayload {
  return canonicalize(payload) as ContentPayload;
}

export function hashContentPayload(payload: ContentPayload): string {
  return hashCanonical(hashedPayload(payload));
}

export function buildPackage(payload: ContentPayload, options: BuildPackageOptions = {}): ContentPackage {
  const manifest = options.manifest ?? DEFAULT_MANIFEST;
  const canonicalPayload = hashedPayload(payload);
  const contentHash = hashCanonical(canonicalPayload);
  const developmentOnly = options.developmentOnly ?? [];
  const buildTimestamp = options.buildTimestamp ?? "";
  return {
    packageId: manifest.packageId,
    packageVersion: manifest.packageVersion,
    schemaVersion: manifest.schemaVersion,
    contentHash: contentHash,
    buildTimestamp: buildTimestamp,
    minimumProtocolVersion: manifest.minimumProtocolVersion,
    developmentOnly: developmentOnly.slice().sort(),
    definitions: canonicalPayload,
    player: canonicalPayload.player,
    items: canonicalPayload.items,
    npcs: canonicalPayload.npcs,
    enemies: canonicalPayload.enemies,
    quests: canonicalPayload.quests,
    zones: canonicalPayload.zones,
    classes: canonicalPayload.classes,
    attributes: canonicalPayload.attributes,
    resources: canonicalPayload.resources,
    derivedStats: canonicalPayload.derivedStats,
    levelCurves: canonicalPayload.levelCurves,
    classProgressions: canonicalPayload.classProgressions,
  };
}

export function buildBundle(payload: ContentPayload, options: BuildPackageOptions = {}): ContentBundle {
  const pkg = buildPackage(payload, options);
  return toContentBundle(pkg);
}

export function toContentBundle(pkg: ContentPackage): ContentBundle {
  return {
    packageId: pkg.packageId,
    packageVersion: pkg.packageVersion,
    schemaVersion: pkg.schemaVersion,
    contentHash: pkg.contentHash,
    minimumProtocolVersion: pkg.minimumProtocolVersion,
    developmentOnly: pkg.developmentOnly,
    player: pkg.player,
    items: pkg.items,
    npcs: pkg.npcs,
    enemies: pkg.enemies,
    quests: pkg.quests,
    zones: pkg.zones,
    classes: pkg.classes,
    attributes: pkg.attributes,
    resources: pkg.resources,
    derivedStats: pkg.derivedStats,
    levelCurves: pkg.levelCurves,
    classProgressions: pkg.classProgressions,
  };
}

export function emitClientJson(bundle: ContentBundle): string {
  return JSON.stringify(canonicalize(bundle), null, 2) + "\n";
}

export function emitServerModule(bundle: ContentBundle): string {
  const payload = {
    player: bundle.player,
    items: bundle.items,
    npcs: bundle.npcs,
    enemies: bundle.enemies,
    quests: bundle.quests,
    zones: bundle.zones,
    classes: bundle.classes,
    attributes: bundle.attributes,
    resources: bundle.resources,
    derivedStats: bundle.derivedStats,
    levelCurves: bundle.levelCurves,
    classProgressions: bundle.classProgressions,
  };
  const body = JSON.stringify(canonicalize(payload), null, 2);
  return [
    "/* Generated by tools/content-build. Do not edit. */",
    "export const packageId = " + JSON.stringify(bundle.packageId) + ";",
    "export const packageVersion = " + JSON.stringify(bundle.packageVersion) + ";",
    "export const schemaVersion = " + String(bundle.schemaVersion) + ";",
    "export const contentHash = " + JSON.stringify(bundle.contentHash) + ";",
    "export const minimumProtocolVersion = " + String(bundle.minimumProtocolVersion) + ";",
    "export const developmentOnly = " + JSON.stringify(bundle.developmentOnly) + " as const;",
    "export const content = " + body + " as const;",
    "export type Content = typeof content;",
    "",
  ].join("\n");
}

export function writeOutputs(serverOut: string, clientOut: string, bundle: ContentBundle): void {
  mkdirSync(dirname(serverOut), { recursive: true });
  mkdirSync(dirname(clientOut), { recursive: true });
  writeFileSync(serverOut, emitServerModule(bundle), "utf8");
  writeFileSync(clientOut, emitClientJson(bundle), "utf8");
}
