import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { canonicalize } from "./canonical";
import { hashCanonical } from "./hash";
import type { ContentBundle, ContentPayload } from "./types";

export const CONTENT_SCHEMA_VERSION = 1;

export function buildBundle(payload: ContentPayload): ContentBundle {
  const canonicalPayload = canonicalize(payload) as ContentPayload;
  const contentHash = hashCanonical(canonicalPayload);
  return { schemaVersion: CONTENT_SCHEMA_VERSION, contentHash, ...canonicalPayload };
}

export function emitClientJson(bundle: ContentBundle): string {
  return JSON.stringify(canonicalize(bundle), null, 2) + "\n";
}

export function emitServerModule(bundle: ContentBundle): string {
  const payload = {
    player: bundle.player,
    items: bundle.items,
    npcs: bundle.npcs,
    enemies: bundle.enemies,
    quests: bundle.quests,
    zones: bundle.zones,
  };
  const body = JSON.stringify(canonicalize(payload), null, 2);
  return [
    "/* Generated by tools/content-build. Do not edit. */",
    "export const schemaVersion = " + String(bundle.schemaVersion) + ";",
    "export const contentHash = " + JSON.stringify(bundle.contentHash) + ";",
    "export const content = " + body + " as const;",
    "export type Content = typeof content;",
    "",
  ].join("\n");
}

export function writeOutputs(serverOut: string, clientOut: string, bundle: ContentBundle): void {
  mkdirSync(dirname(serverOut), { recursive: true });
  mkdirSync(dirname(clientOut), { recursive: true });
  writeFileSync(serverOut, emitServerModule(bundle), "utf8");
  writeFileSync(clientOut, emitClientJson(bundle), "utf8");
}
