# Clean-setup gate: content, server, client, then the two-client e2e journey.
$ErrorActionPreference = "Stop"
. "$PSScriptRoot\_common.ps1"
Write-Host "== setup =="
Invoke-RepoScript "setup.ps1"
Write-Host "== test-content =="
Invoke-RepoScript "test-content.ps1"
Write-Host "== test-audit =="
Invoke-RepoScript "test-audit.ps1"
Write-Host "== test-server =="
Invoke-RepoScript "test-server.ps1"
Write-Host "== test-account-compat =="
Invoke-RepoScript "test-account-compat.ps1" -ArgumentList @("-SkipDomain")
Write-Host "== test-client =="
Invoke-RepoScript "test-client.ps1"
Write-Host "== test-e2e =="
Invoke-RepoScript "test-e2e.ps1"
Write-Host "== test-capacity =="
Invoke-RepoScript "test-capacity.ps1"
Write-Host "== test-soak =="
Invoke-RepoScript "test-soak.ps1"
Write-Host "== test-cert-journey =="
Invoke-RepoScript "test-cert-journey.ps1"
Write-Host "== test-backup =="
Invoke-RepoScript "test-backup.ps1"
Write-Host "test-all passed."
